# Copyright (c) Jupyter Development Team.
# Distributed under the terms of the Modified BSD License.
ARG BASE_CONTAINER=ccros/jupyterlab-notebook:python-3.8.5b
FROM $BASE_CONTAINER

USER root

RUN apt-get update && apt-get install -yq --no-install-recommends \
    vim \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER $NB_UID

WORKDIR $HOME
