FROM cschranz/gpu-jupyter:v1.3_cuda-10.1_ubuntu-18.04

USER root

RUN apt-get update && apt-get install -yq --no-install-recommends \
    vim \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

USER $NB_UID

RUN conda config --system --prepend channels bioconda && \
    conda config --system --prepend channels conda-forge && \
    conda install --quiet --yes \
    'jupytext' \
    'pre-commit' \
    'nb_conda_kernels' && \
    conda clean --all -f -y

USER root

RUN jupyter labextension install @jupyterlab/theme-dark-extension --no-build && \
    jupyter labextension install @krassowski/jupyterlab_go_to_definition --no-build && \
    jupyter labextension install jupyterlab-jupytext@1.2.2 --no-build && \
    jupyter lab build -y && \
    jupyter lab clean -y && \
    npm cache clean --force && \
    rm -rf "/home/${NB_USER}/.cache/yarn" && \
    rm -rf "/home/${NB_USER}/.node-gyp" && \
    fix-permissions "${CONDA_DIR}" && \
    fix-permissions "/home/${NB_USER}"

RUN echo "export PATH=/usr/local/cuda-10.1/bin${PATH:+:${PATH}}" >> /etc/profile && \
    echo "export LD_LIBRARY_PATH=/usr/local/cuda-10.1/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}" >> /etc/profile

USER $NB_UID

WORKDIR $HOME
